on:
  workflow_dispatch:

env:
  CONFIG: |
    {
      "stack": "go",
      "pacticipants": {
        "consumer": [],
        "provider": [
          "analyze-api"
        ]
      },
      "service": "analyze-api"
    }

jobs:
  start:
    outputs:
      config: ${{ steps.parse.outputs.config }}
    runs-on: ubuntu-latest
    steps:
      - name: Parse
        id: parse
        run: |
          set -x

          echo "config=$(echo $CONFIG | jq -c '.')" >> $GITHUB_OUTPUT
  call:
    needs: [ start ]
    uses: ./.github/workflows/reproduction.yaml
    with:
      service_config: ${{ needs.start.outputs.config }}
  