on:
  workflow_dispatch:
  
env: 
  INPUT: |
    {
      "array": [
        "one",
        "two",
        "three"
      ]
    }
jobs:
  parse:
    outputs: 
      array: ${{ steps.parse.outputs.array }}
    runs-on: ubuntu-latest
    steps:
      - name: Parse
        id: parse
        run: |
          echo "array=$(echo ${{ INPUT }} | jq -r '.array')" >> $GITHUB_OUTPUT
  use:
    needs: [ parse ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        item: ${{ fromJSON(needs.parse.outputs.array) }}
    steps:
      - name: Use
        run: echo ${{ matrix.item }}