on:
  workflow_dispatch:
  
env: 
  CONFIG: |
    {
      "stack": "go",
      "pacticipants": {
        "consumer": [],
        "provider": [
          "analyze-api"
        ]
      },
      "service": "analyze-api"
    }
jobs:
  parse:
    outputs: 
      stack: ${{ steps.parse.outputs.stack }}
      consumers: ${{ steps.parse.outputs.consumers }}
      providers: ${{ steps.parse.outputs.providers }}
    runs-on: ubuntu-latest
    steps:
      - name: Parse
        id: parse
        run: |
          set -x

          echo "stack=$(echo $CONFIG | jq -r '.stack')" >> $GITHUB_OUTPUT
          echo "consumers=$(echo $CONFIG | jq -c '.pacticipants.consumer')" >> $GITHUB_OUTPUT
          echo "providers=$(echo $CONFIG | jq -c '.pacticipants.provider')" >> $GITHUB_OUTPUT
  
  use:
    needs: [ parse ]
    strategy:
      fail-fast: false
      matrix:
        provider: ${{ fromJSON(needs.parse.outputs.providers) }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Running check for ${{ matrix.provider }}"

  call:
    needs: [ parse ]
    strategy:
      fail-fast: false
      matrix:
        provider: ${{ fromJSON(needs.parse.outputs.providers) }}
    uses: ./.github/workflows/called.yaml
    with:
      provider: ${{ matrix.provider }}